[package]
name = "bookie-backend-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "^0.7", features = ["d1"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bookie_core = { path = "../../packages/core" }
ulid = "1.1"
console_error_panic_hook = "0.1"
uuid = { version = "1.7", features = ["v4", "js"] }
chrono = "0.4"
serde_urlencoded = "0.7"
base64 = "0.21"
getrandom = { version = "0.3.4", features = ["wasm_js"] }
async-trait = "0.1"

[profile.release]
opt-level = "z"   # Optimize for size
lto = true        # Enable Link Time Optimization
codegen-units = 1 # Reduce number of codegen units to increase optimizations
