name = "bookie-backend-web"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
command = "cargo install worker-build && worker-build --release"

[build.upload]
format = "modules"
dir = "build/worker"
main = "./shim.mjs"

[[d1_databases]]
binding = "DB"
database_name = "bookie"
database_id = "preview_database_id"

[vars]
ENVIRONMENT = "development"
